### ISSUE TITLE
It should be possible to install CNI plugin through Kubernetes API

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2448]
This would imply that that we need the router to run as a DaemonSet.

**Comment by bboreham** [comment]
Could you expand a little bit?  What sequence of commands would you expect to run to achieve this?

**Comment by bboreham** [comment]
I looked into this; currently kubelet will fail at startup unless there is at least one CNI network configured.

https://github.com/kubernetes/kubernetes/pull/28178 should fix that.

**Comment by rade** [comment]
@bboreham what is the answer to your own question? i.e. post the fix you mention, what sequence of commands would we envisage?

**Comment by bboreham** [comment]
I have now successfully tested with a DaemonSet using this manifest:

````
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: weave-net
spec:
  template:
    metadata:
      labels:
        name: weave-net
    spec:
      hostNetwork: true
      containers:
        - name: weave
          image: weaveworks/weave-kube:1.6.1
          command:
            - /home/weave/launch.sh
          env:
            - name: WEAVE_VERSION
              value: kube-test
          securityContext:
            privileged: true
          volumeMounts:
            - name: weavedb
              mountPath: /weavedb
            - name: cni-bin
              mountPath: /opt
            - name: cni-conf
              mountPath: /etc
          securityContext:
            privileged: true
      restartPolicy: Always
      volumes:
        - name: weavedb
          emptyDir: {}
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
````

This uses a container built off `weaveexec`, containing a program to fetch peer names via the Kubernetes API and this startup script:

````
#!/bin/sh

set -e

/home/weave/weave --local setup-cni
/home/weave/weave --local create-bridge

exec /home/weave/weaver --port=6783 --datapath=datapath \
     --http-addr=127.0.0.1:6784 --docker-api='' --no-dns \
     --ipalloc-range=10.244.0.0/14 \
     --name=$(cat /sys/class/net/weave/address) $(/home/weave/kube-peers)
````
