### ISSUE TITLE
How do I query weave for its configuration?

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#259]
I am writing a Facter fact for the hesco/weave puppet module.  For those not familiar, a fact is a means to query a machine to learn about it and its configuration.  For instance `facter -p macaddress_eth0` returns `00:30:48:c0:80:48' on one of my docker hosts.  

At this point I have a fact which returns a complex json data structure populated by the data extracted from `weave ps` and `docker inspect` queries.  The last piece of this I have yet to complete is generating this data (rendered here as yaml):

```
  weave_networked_containers: 
    docker_host: 
      hostname: dockerhost002.example.com
      weave_ip: "10.0.1.2/24"
      weave_mac: "7a:06:2f:53:2d:5f"
      peered_device: not_yet_implemented
      peered_ip: not_yet_implemented
      peers: not_yet_implemented
```

I've looked at `weave status` but so far do not yet understand its structure well enough to discern the difference between the local peered_ip and the ip's of the remote peers.  If I can sort out which IP is the local peer, I can discern the matching local peered_device.  At this point I do not actually have a use case for these, but it seems appropriate to include these keys in the interest of completeness.  The rest of this has been fairly straight-forward, even for someone who only dabbles with ruby when I have to.  

I'm seeking advise on how to implement those final three items.  Is that possible?  Any help would be appreciated.  Thanks.
