### ISSUE TITLE
Recent CoreOS breaks Weave Net

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2601]
It seems from https://github.com/kontena/kontena/issues/1285, https://github.com/kontena/kontena/issues/1264 and https://github.com/coreos/bugs/issues/1554 that a CoreOS change has resulted in `systemd-networkd` re-configuring the virtual ethernet (veth) devices that Weave creates, resulting in them being disconnected from the weave bridge and hence breaking communication.

Further, the CoreOS config requests a DHCP address for the `weave` bridge which we don't want.

One commenter asserts this is a "regression with CoreOS stable 1122.3.0 -> 1185.3.0".

Edit: to detect if this is happening, run

    ip link show type veth | grep vethwe | grep -v master

any output will indicate a device that has been detached from the bridge.

**Comment by bboreham** [comment]
https://github.com/kontena/kontena/issues/1264 collects a set of changes to systemd-network configuration that form a workaround.

**Comment by bboreham** [comment]
I suspect a simpler workaround would be to add a networkd config file `/etc/systemd/network/10-weave-veth.network` requesting systemd to add devices named `vethwe*` to the `weave` bridge.  This will duplicate what Weave itself does, but at least it won't be so destructive.  

We would still need a file like `/etc/systemd/network/10-weave-bridge.network` requesting no changes to the `weave` bridge itself.

I haven't tried this.

**Comment by SpComb** [comment]
> kontena/kontena#1264 collects a set of changes to systemd-network configuration that form a workaround.

Please note that these proposed changes are pretty much untested on my part, I have not yet been able to reproduce this vethwe <-> systemd-networkd race myself.

**Comment by SpComb** [comment]
> We would still need a file like /etc/systemd/network/10-weave-bridge.network requesting no changes to the weave bridge itself.

Kontena actually already ships this kind of systemd-networkd configuration: https://github.com/kontena/kontena-plugin-digitalocean/blob/v0.2.0/lib/kontena/machine/digital_ocean/cloudinit.yml#L30-L37

```yaml
coreos:
  units:
    - name: 10-weave.network
      runtime: false
      content: |
        [Match]
        Type=bridge
        Name=weave*
        [Network]
```

**Comment by bboreham** [comment]
> Please note that these proposed changes are pretty much untested on my part

I tested them, as described at https://github.com/kontena/kontena/issues/1285#issuecomment-258905209 (including the bridge override)

**Comment by SpComb** [comment]
I fixed the broken `zz-default.network` example in https://github.com/kontena/kontena/issues/1264.

> We would still need a file like /etc/systemd/network/10-weave-bridge.network requesting no changes to the weave bridge itself.

If you override the `zz-default.network` to not match the weave bridge and veth interfaces, then the need for a `10-weave-bridge.network` also goes away.

---

Here's my recommended CoreOS cloud-config: https://github.com/kontena/kontena/issues/1264#issuecomment-259381851

This changes the `zz-default.network` to override the `[Match]` to not match the Docker/Weave bridge/veth interfaces, and then masks out the `50-docker.network` and `50-docker-veth.network` units that are not longer needed.

```yaml
coreos:
  units:
    - name: 50-docker.network
      mask: true
    - name: 50-docker-veth.network
      mask: true
    - name: zz-default.network
      runtime: false
      content: |
        # default should not match virtual Docker/weave bridge/veth network interfaces
        [Match]
        Name=eth*

        [Network]
        DHCP=yes

        [DHCP]
        UseMTU=true
        UseDomains=true
```

This ensures that systemd-networkd will leave all Docker/weave bridge/veth network interfaces unmanaged: `networkctl status`

```
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 eth0             ether              routable    configured
  3 eth1             ether              routable    configuring
  4 docker0          ether              routable    unmanaged 
  5 datapath         ether              degraded    unmanaged 
  7 weave            ether              routable    unmanaged 
  8 dummy0           ether              off         unmanaged 
 10 vethwe-datapath  ether              degraded    unmanaged 
 11 vethwe-bridge    ether              degraded    unmanaged 
 12 vxlan-6784       ether              degraded    unmanaged 
 14 vethc7f0c57      ether              degraded    unmanaged 
```


The `zz-default.network` `[Match]` section may need changes depending on the interface naming used by the platform. The following trick *might* also work to only match "pyhsical" network interfaces?

```
[Match]
Path=*
```
