### ISSUE TITLE
Support configurable log level in weave-npc

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2628]
_From @awh on October 14, 2016 8:43_

Via a configmap or an environment variable.

_Copied from original issue: weaveworks/weave-npc#20_

**Comment by bboreham** [comment]
I believe the crux of this issue is that while the `weave-npc` program supports our usual command-line flag `--log-level`, it is nontrivial to edit this into the yaml for the DaemonSet.

Our config generator at cloud.weave.works allows you to add environment variables, so perhaps that is the way to go.

**Comment by hairyhenderson** [comment]
For anyone else who came to this from a google search, this can be accomplished by patching the PodSpec in the DaemonSet to add `--log-level=error` to the `args` list.

I did something like this:

_weave-patch.yml:_
```yaml
kind: DaemonSet
metadata:
  name: weave-net
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: weave-npc
          args:
            - --log-level=error
```

```console
$ kubectl patch -n kube-system daemonset weave-net --patch "$(< weave-patch.yml)"
```
