### ISSUE TITLE
Can not securely use GELF logging driver within weave network

### ISSUE THREAD

**Issue by olegabr** [weaveworks/weave#2730]
I'm trying to use a logging server to collect docker containers logs. I'm also using weave network with encryption enabled. I've tried to specify local weave name for the logging server, but it responds with an error that service with this name can not be found.

I've found that it is the same issue others reported here: https://github.com/docker/docker/issues/20370.

I just wander if there is some workaround to do it in the `weave` ecosystem. It is important to me because for now I need to open a one more port and secure it with `iptables` between all my servers where my containers live. I would better avoid that if it is possible.

uname -a
------------

```
Linux myserver 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

iptables-save
-----------------

```
# Generated by iptables-save v1.6.0 on Fri Jan 13 06:19:50 2017
*filter
:INPUT DROP [4424:248962]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [169404:129140886]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
-A INPUT -p icmp -f -j DROP
-A INPUT -p tcp -m conntrack --ctstate NEW -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -j DROP
-A INPUT -p tcp -m conntrack --ctstate INVALID,NEW -m tcp --tcp-flags SYN,ACK SYN,ACK -j REJECT --reject-with tcp-reset
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK RST -m limit --limit 1/sec -j ACCEPT
-A INPUT -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 12345 --tcp-flags FIN,SYN,RST,ACK SYN -m recent --set --name blacklist --mask 255.255.255.255 --rsource
-A INPUT -p tcp -m tcp --dport 12345 --tcp-flags FIN,SYN,RST,ACK SYN -m recent --update --seconds 600 --hitcount 10 --name blacklist --mask 255.255.255.255 --rsource -j DROP
-A INPUT -p tcp -m tcp --dport 12345 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1111 -j ACCEPT
-A INPUT -s 111.111.111.111/32 -p tcp -m tcp --dport 6783 -j ACCEPT
-A INPUT -s 111.111.111.111/32 -p udp -m udp --dport 6783 -j ACCEPT
-A INPUT -s 111.111.111.111/32 -p udp -m udp --dport 6784 -j ACCEPT
-A INPUT -s 222.222.222.222/32 -p tcp -m tcp --dport 6783 -j ACCEPT
-A INPUT -s 222.222.222.222/32 -p udp -m udp --dport 6783 -j ACCEPT
-A INPUT -s 222.222.222.222/32 -p udp -m udp --dport 6784 -j ACCEPT
-A INPUT -s 123.123.123.123/32 -p tcp -m tcp --dport 6783 -j ACCEPT
-A INPUT -s 123.123.123.123/32 -p udp -m udp --dport 6783 -j ACCEPT
-A INPUT -s 123.123.123.123/32 -p udp -m udp --dport 6784 -j ACCEPT
-A INPUT -d 172.17.0.1/32 -i docker0 -p tcp -m tcp --dport 6783 -j DROP
-A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6783 -j DROP
-A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6784 -j DROP
-A INPUT -i docker0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i docker0 -p tcp -m tcp --dport 53 -j ACCEPT
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o weave -j DROP
-A FORWARD -i weave -o weave -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A DOCKER -d 172.17.0.10/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9876 -j ACCEPT
-A DOCKER -d 172.17.0.10/32 ! -i docker0 -o docker0 -p udp -m udp --dport 21120 -j ACCEPT
-A DOCKER -d 172.18.0.3/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 3547 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 1111 -j ACCEPT
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -j RETURN
COMMIT
# Completed on Fri Jan 13 06:19:50 2017
# Generated by iptables-save v1.6.0 on Fri Jan 13 06:19:50 2017
*nat
:PREROUTING ACCEPT [19480:1170556]
:INPUT ACCEPT [5379:352455]
:OUTPUT ACCEPT [5859:2412636]
:POSTROUTING ACCEPT [17345:3088386]
:DOCKER - [0:0]
:WEAVE - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.18.0.0/16 ! -o docker_gwbridge -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -j WEAVE
-A POSTROUTING -s 172.17.0.10/32 -d 172.17.0.10/32 -p tcp -m tcp --dport 9876 -j MASQUERADE
-A POSTROUTING -s 172.17.0.10/32 -d 172.17.0.10/32 -p udp -m udp --dport 21120 -j MASQUERADE
-A POSTROUTING -s 172.18.0.3/32 -d 172.18.0.3/32 -p tcp -m tcp --dport 3547 -j MASQUERADE
-A POSTROUTING -s 172.17.0.3/32 -d 172.17.0.3/32 -p tcp -m tcp --dport 1111 -j MASQUERADE
-A DOCKER -i docker_gwbridge -j RETURN
-A DOCKER -i docker0 -j RETURN
-A DOCKER -d 127.0.0.1/32 ! -i docker0 -p tcp -m tcp --dport 9876 -j DNAT --to-destination 172.17.0.10:9876
-A DOCKER -d 127.0.0.1/32 ! -i docker0 -p udp -m udp --dport 21120 -j DNAT --to-destination 172.17.0.10:21120
-A DOCKER -d 127.0.0.1/32 ! -i docker_gwbridge -p tcp -m tcp --dport 3547 -j DNAT --to-destination 172.18.0.3:3547
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 1111 -j DNAT --to-destination 172.17.0.3:1111
COMMIT
# Completed on Fri Jan 13 06:19:50 2017
```

**Comment by awh** [comment]
>  I've tried to specify local weave name for the logging server, but it responds with an error that service with this name can not be found.

@olegabr is your logging server running in a container attached to the weave network or is it just running directly on a host?

**Comment by olegabr** [comment]
Yes, my logger server is attached to the same weave network as all other containers that needs to use it.

The logging server
------------------------

```yml
version: '2'
services:
  mongo:
    image: mongo:3
    hostname: mongo.${SERVER_NAME}.weave.local
    network_mode: "bridge"
    volumes:
      - mongo_data:/data/db
  elasticsearch:
    image: elasticsearch:2
    hostname: elasticsearch.${SERVER_NAME}.weave.local
    network_mode: "bridge"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.1.1-1
    hostname: graylog.${SERVER_NAME}.weave.local
    network_mode: "bridge"
    environment:
      GRAYLOG_PASSWORD_SECRET: 123456
      GRAYLOG_ROOT_PASSWORD_SHA2: shahere
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      GRAYLOG_CONTENT_PACKS_AUTO_LOAD: grok-patterns.json,udp-input-graylog.json
      GRAYLOG_CONTENT_PACKS_LOADER_ENABLED: "true"
      GRAYLOG_CONTENT_PACKS_DIR: data/contentpacks
    depends_on:
      - mongo
      - elasticsearch
    links:
      - mongo
      - elasticsearch
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:12201/udp:12201/udp"
    volumes:
      - log_data:/usr/share/graylog/data/journal
      - graylog-tmp:/tmp
networks:
    default:
        external:
            name: weave
volumes:
  mongo_data:
  elasticsearch_data:
  log_data:
  graylog-tmp:
```

Some service
-----------------

```yml
version: '2'
services:
    myservice:
        image: jwilder/whoami
        hostname: myservice.${SERVER_NAME}.weave.local
        network_mode: "bridge"
        logging:
            driver: gelf
            options:
               tag: "myservice.${SERVER_NAME}"
               gelf-address: "udp://127.0.0.1:12201"
#               gelf-address: "udp://graylog.B1.weave.local:12201"

networks:
    default:
        external:
            name: weave
```

Note that I need the commented line `gelf-address: "udp://graylog.B1.weave.local:12201"` to work. I've tried all variants of graylog.B1.weave.local, graylog.B1.weave, graylog.B1, graylog with no success. In other case I need to specify the logging server IP address. It is `127.0.0.1` there, but in a multi-server configuration it would be the real machine IP. And I would need to expose the 12201/udp port on this machine and add firewall rules to restrict access to it only from those machines where my other services run.
The problem here is that this need to expose port defeats the whole purpose of using weave in the first place - to simplify the secure multi-server docker services deployment. I need one more open port and one more devops task.

**Comment by awh** [comment]
@olegabr it'd be useful to have some more context - is this happening on an actual multi-server deployment or are you just prototyping on a single node at this point? Are you using Swarm, and if so, which version? What is the role of `$SERVER_NAME` in your compose file?

Please also try running 

```
sudo weave status dns
```

on the host(s) to see if the name is being registered with Weave's DNS properly.

**Comment by olegabr** [comment]
```
$ weave status dns|grep graylog
graylog.B1   10.40.0.11      de5efc888bcc 00:00:00:00:00:d1
```

There are three bare metal servers now: B1, F1, W1.

The `SERVER_NAME` is B1 for backend server 1, F1 for frontend server 1 etc.

The `Swarm` is not used here.

The test service is running on the same server with the graylog2.

**Comment by awh** [comment]
@olegabr there are two problems here, both of which stem from the fact that the logging driver configuration affects the Docker daemon, which is not part of the container network (as mentioned here https://github.com/docker/docker/issues/20370#issuecomment-257739121):

1. It's tricky to arrange for things in the host network namespace to resolve weaveDNS names via the system resolver
1. Things running in the host network namespace are not connected to the overlay network

Having said that, there are some weave features that might let you do what you want:

1. You can configure your host resolv.confs to point at Weave's DNS server (it listens on the Docker bridge IP, which is stable across restarts) and configure Weave's DNS to fallback requests to your normal DNS servers. Caveat: your system won't be able to resolve names until the Weave router has started!
1. If you run `weave expose` on each host they will get their own IP on the weave network - the Docker logging driver should then be able to connect directly to container IPs (including your logging server)

**Comment by olegabr** [comment]
Thank you, @awh!

The `weave expose` is a key. The problem is fixed now.

1. in a startup script on each server add the `weave expose` call;
2. in the same script add a line like this: `export LOGSERVER_ADDRESS=$(weave dns-lookup graylog.B1.weave.local)`
3. use it in the docker-compose file like this:
```yml
version: '2'
services:
    service:
        image: some-service
        hostname: service.${SERVER_NAME}.weave.local
        network_mode: "bridge"
        logging:
            driver: gelf
            options:
                tag: "service.${SERVER_NAME}"
                gelf-address: "udp://${LOGSERVER_ADDRESS}:12201"
```

Hope it would help someone else.
