### ISSUE TITLE
Running WeaveNet behind a proxy

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2766]
I am running WeaveNet under Kubernetes, behind a corporate proxy.
In the weaveworks/weave-kube container logs I see the message:

````
INFO: 2017/02/01 16:54:00.581681 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-53-generic&os=linux&signature=zmRIfHfyP%2BuXYK8z%2Ba1dYViNOW8mK2lKN8nRE8V2%2BwE%3D&version=1.8.2: dial tcp 172.217.17.147:443: getsockopt: connection refused
````

As such the issue seems to be no problem, because the weave net functions for the rest okay.

I suspect that the container needs the environment variable HTTPS_PROXY set.

When I docker exec into the container and do:
````
/home/weave # curl https://checkpoint-api.weave.works
````
the call hangs.

When I do:
````
/home/weave # export HTTPS_PROXY=https://xx.xx.xx:8080
/home/weave # curl https://checkpoint-api.weave.works
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
/home/weave #
````
it returns some html code.

I decided to add the proxy env settings to weave-daemonset.yaml:
````
      containers:
        - name: weave
          env:
            - name: EXPECT_NPC
              value: "0"
            - name: HTTP_PROXY
              value: "http://xx.xx.xx:8080"
            - name: HTTPS_PROXY
              value: "https://xx.xx.xx:8080"
````

Next, applied the weave-daemonset.yaml and restarted the pods one by one.

Unfortunately, weave-net doesn't like the proxy settings and the pods continuously terminate and restart.

Any suggestions how to get this working from behind a corporate proxy?
