### ISSUE TITLE
Quorum not being reached 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#2767]
Running the network in Kubernetes on Bare Metal. Set the IPALLOC_RANGE in the weave-daemonset.yaml with the following: 

```
containers:
        - name: weave
          env:
          - name: IPALLOC_RANGE
            value: 192.168.0.0/16
          image: weaveworks/weave-kube:latest
          imagePullPolicy: Always
```

Logs say for all three containers same collision: 

```INFO: 2017/02/02 20:24:09.535473 ->[147.75.100.177:56831|ea:ba:c8:b5:52:f9(kube-node-2.local.lan)]: connection shutting down due to error: local "ea:ba:c8:b5:52:f9(kube-node-2.local.lan)" and remote "ea:ba:c8:b5:52:f9(kube-node-1.local.lan)" peer names collision```

I can see all of the weave containers in the container view (associated with each of the three hosts) as shown below: 

![screen shot 2017-02-02 at 2 40 52 pm](https://cloud.githubusercontent.com/assets/13420383/22567471/a26af49a-e955-11e6-99e7-671cae53c388.png)

But when I switch to the Weave Net view all I see is an error and status waiting for quorum: 

![screen shot 2017-02-02 at 2 57 18 pm](https://cloud.githubusercontent.com/assets/13420383/22567949/77b3e3e0-e957-11e6-9c00-f7df45ed70b5.png)
