### ISSUE TITLE
Weave Net: cannot set MAC address

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2870]
For one of my containers I need to specify a certain MAC Address. This seems not possible with Weave:

````
bergtwvd@app-docker02:~$ docker network create -d weave WWW
304082cb004435b221f8db1f97304eb6545d3806541bf319a4442518f2f5ee97
bergtwvd@app-docker02:~$ docker run --network=WWW --mac-address="00:18:8B:0D:4F:0B"  -ti weaveworks/ubuntu
docker: Error response from daemon: failed to create endpoint suspicious_swirles on network WWW: driver modified interface MAC address: endpoint interface MAC address present (00:18:8b:0d:4f:0b). Cannot be modified with a6:7b:00:9a:66:01.; rolled back.
bergtwvd@app-docker02:~$
````

When I use standard docker overlay, this works fine:
````
bergtwvd@app-docker02:~$ docker network create -d overlay OOO
61751eeafdc204ccc42e4bfc724b68ed46bf4b75297ae5a19289ff464816a163
bergtwvd@app-docker02:~$ docker run --network=OOO --mac-address="00:18:8B:0D:4F:0B"  -ti weaveworks/ubuntu
root@83e934fadf39:/# uname -a
Linux 83e934fadf39 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@83e934fadf39:/#
````

I recall this worked in the past.

**Comment by bergtwvd** [comment]
After a little further exploration of options:

If I use the weave proxy server to start a container I am able to assign a MAC address to the eth0 interface.  This will get my app going with the license. The container will also get an ethwe interface. See https://www.weave.works/docs/net/latest/weave-docker-api.  This works from the command line, and I recall this was the way I used to start containers in the old days, before the existence of network plugins and before docker compose file version 2.0.

If I use docker-compose file version 2/3, then this does not work, even going through the proxy; seems related to the fact that docker compose creates a bridge network to. I need to revert to compose file version 1 to create a composition via the proxy, and assign a MAC address !  So, onyly compose file version 1 works, not ideal.  :-(

**Comment by bergtwvd** [comment]
Some other related issues:
https://github.com/weaveworks/weave/issues/2690
https://github.com/weaveworks/weave/issues/2718

**Comment by marccarre** [comment]
@bergtwvd, would you mind sharing a minimalistic example of:
- a working Docker compose v1 file?
- a non-working Docker compose v2/3 file?

This would help replicating your exact issue and, potentially, fixing it. Thanks!

**Comment by bergtwvd** [comment]
For test purposes I use the following compositions:

````
bergtwvd@app-docker02:~$ more test.v2.overlay.yml
version: '2'

services:
 test:
  image: busybox
  command: sleep 3600
  mac_address: 00:18:8B:0D:4F:0B
  networks:
  - hello

networks:
 hello:
  driver: overlay
````

````
bergtwvd@app-docker02:~$ more test.v2.weave.yml
version: '2'

services:
 test:
  image: busybox
  command: sleep 3600
  mac_address: 00:18:8B:0D:4F:0B
  networks:
  - hello

networks:
 hello:
  driver: weave
````

````
bergtwvd@app-docker02:~$ more test.v1.yml

 test:
  image: busybox
  command: sleep 3600
  mac_address: 00:18:8B:0D:4F:0B
````

Test: Docker Compose v2 file, use docker overlay network (**OK**)
````
bergtwvd@app-docker02:~$ docker-compose -f test.v2.overlay.yml up
Creating network "bergtwvd_hello" with driver "overlay"
Creating bergtwvd_test_1
Attaching to bergtwvd_test_1
````

Test: Docker Compose v2 file, use weave overlay network (via weave plugin) (**ERROR**)
````
bergtwvd@app-docker02:~$ docker-compose -f test.v2.weave.yml up
Creating network "bergtwvd_hello" with driver "weave"
Creating bergtwvd_test_1

ERROR: for test  failed to create endpoint bergtwvd_test_1 on network bergtwvd_hello: driver modified interface MAC address: endpoint interface MAC address present (00:18:8b:0d:4f:0b). Cannot be modified with 5e:79:b4:e7:54:86.; rolled back
Attaching to
````

Test: Docker Compose v2 file, use weave overlay network (via weave proxy) (**ERROR**)
````
bergtwvd@app-docker02:~$ DOCKER_HOST=:12375 docker-compose -f test.v2.weave.yml up
Creating network "bergtwvd_hello" with driver "weave"
Creating bergtwvd_test_1

ERROR: for test  failed to create endpoint bergtwvd_test_1 on network bergtwvd_hello: driver modified interface MAC address: endpoint interface MAC address present (00:18:8b:0d:4f:0b). Cannot be modified with fe:03:bb:89:2e:db.; rolled back
Attaching to
````

Test: Docker Compose v1 file, use weave overlay network (via weave proxy) (**OK**)
````
bergtwvd@app-docker02:~$ DOCKER_HOST=:12375 docker-compose -f test.v1.yml up
Creating bergtwvd_test_1
Attaching to bergtwvd_test_1
````
