### ISSUE TITLE
Feature Request: Assign IP via WEAVE_CIDR for weaveworks/net-plugin

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave#3109]
why:
A single-container Docker Service should be able to specify its IP address via WEAVE_CIDR similar to `docker run`. This is important to us when we deploy a set of stateful services (for example DB clusters, which are required fixed IP addresses for their stability).

Currently, there is no code in `cni.go` or `driver.go` which detects a parameter or an environment variable to allow this. 

The following docker-stack.yml with this command `docker stack deploy app1 -c docker-stack.yml` should allow fixing each service IP address.
```
version: '3.3'

networks:
  app:
    driver: weaveworks/net-plugin:latest
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.32.1.0/24

services:
  nginx-1:
    image: nginx
    environment:
      - WEAVE_CIDR=10.32.1.101/24
    networks:
      app:
        ipv4_address: 10.32.1.101
        aliases:
          - pingme
    ports:
      - 0:80

  nginx-2:
    image: nginx
    environment:
      - WEAVE_CIDR=10.32.1.102/24
    networks:
      app:
        ipv4_address: 10.32.1.102
        aliases:
          - pingme
    ports:
      - 0:80

  nginx-3:
    image: nginx
    environment:
      - WEAVE_CIDR=10.32.1.103/24
    networks:
      app:
        ipv4_address: 10.32.1.103
        aliases:
          - pingme
    ports:
      - 0:80
```

Version Info:
  * `docker 17.06.1-ce` swarm mode
  * `weaveworks/net-plugin 2.0.4`
