### ISSUE TITLE
weave-net not working on AWS when using K8s yaml config

### ISSUE THREAD

**Issue by jeroenjacobs1205** [weaveworks/weave#3112]
We have 2 kubernetes clusters, one running on AWS, the other in our own datacenter.

We use the same yaml config to deploy the DaemonSet on both clusters. We have no issues on our internal cluster, but on the AWS cluster, pod networking is not working.

Theses are the version numbers:

Weave: 2.0.4
Kubernetes: 1.6.6
OS: CentOS 7

(both clusters use the same versions of all components)

Important: we do not use VPC backend of Weave, as we don't want to use this. We want an identical setup on both environments.

This are the pods running on the AWS cluster:

```
[centos@ip-10-8-31-56 ~]$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                         READY     STATUS    RESTARTS   AGE       IP            NODE
kube-system   heapster-3527417143-hgl69                    1/1       Running   0          31m       10.32.0.2     ip-10-8-30-121
kube-system   kube-dns-3664836949-lgvkv                    3/3       Running   0          32m       10.40.0.2     ip-10-8-31-84
kube-system   kube-dns-3664836949-v2116                    3/3       Running   0          32m       10.40.0.1     ip-10-8-31-84
kube-system   kubernetes-dashboard-31289456-csnf7          1/1       Running   0          3m        10.40.0.3     ip-10-8-31-84
kube-system   traefik-ingress-controller-967314268-dc5r5   1/1       Running   0          31m       10.32.0.4     ip-10-8-30-121
kube-system   weave-net-slff0                              2/2       Running   0          32m       10.8.31.84    ip-10-8-31-84
kube-system   weave-net-zvr8b                              2/2       Running   0          32m       10.8.30.121   ip-10-8-30-121
```
However, dashboard cannot connect to another pod:

```
[centos@ip-10-8-31-56 ~]$ kubectl logs kubernetes-dashboard-31289456-csnf7 -n kube-system
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.6.6
No request provided. Skipping authorization header
Creating in-cluster Heapster client
Could not enable metric client: Health check failed: an error on the server ("Error: 'dial tcp 10.32.0.2:8082: getsockopt: connection timed out'\nTrying to reach: 'http://10.32.0.2:8082/healthz'") has prevented the request from succeeding (get services heapster). Continuing.

```
Despite the fact we use the same yaml config for deploying Weave, I notice the CNI config that is generated seems to be different.

On the internal cluster:

```
{
    "name": "weave",
    "type": "weave-net"
}

```

On the AWS cluster:

```
{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": true
}
```

There might be a difference in the CNI version we are using on both clusters, but I still need to investigate that. On the AWS cluster the CNI release is 0.6.0

This is the yaml file we use to deploy the DaemonSet:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weave-net
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-net
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weave-net
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-net
subjects:
- kind: ServiceAccount
  name: weave-net
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: weave-net
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: weave-net
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: weave
          env:
            - name: IPALLOC_RANGE
              value: 10.32.0.0/12

          image: weaveworks/weave-kube:2.0.4
          command:
            - /home/weave/launch.sh
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 6784
          securityContext:
            privileged: true
          volumeMounts:
            - name: weavedb
              mountPath: /weavedb
            - name: cni-bin
              mountPath: /host/opt
            - name: cni-bin2
              mountPath: /host/home
            - name: cni-conf
              mountPath: /host/etc
            - name: dbus
              mountPath: /host/var/lib/dbus
            - name: lib-modules
              mountPath: /lib/modules
          resources:
            requests:
              cpu: 10m
        - name: weave-npc
          image: weaveworks/weave-npc:2.0.4
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      restartPolicy: Always
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: weave-net
      securityContext:
        seLinuxOptions:
          type: spc_t
      volumes:
        - name: weavedb
          emptyDir: {}
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-bin2
          hostPath:
            path: /home
        - name: cni-conf
          hostPath:
            path: /etc
        - name: dbus
          hostPath:
            path: /var/lib/dbus
        - name: lib-modules
          hostPath:
            path: /lib/modules
  updateStrategy:
    type: RollingUpdate

```
