### ISSUE TITLE
weave crash because maintain connection to dead apiservers in multimaster cluster

### ISSUE THREAD

**Issue by fvigotti** [weaveworks/weave#3126]
## What you expected to happen?
weave restart when node restart 

## What happened?
if not all masters are up, some weave pods doesn't restart , because cannot connect to apiserver ( yeah 1/3 of apiserver is down, but 2/3 are up! so he should recover aswell! ) this leave whole node networking down causing cascading issues..

## How to reproduce it?
see here down in description

## Anything else we need to know?
bare metal servers, installed manually (everything else works, weavescope is ok, service account are ok no other errors in kubelets ( except those caused by weave networking missing when I trigger the problem ) 

## Versions:

```
$ weave version 2.0.4
$ docker version 1.12.6
$ uname -a  4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version v1.6.7+coreos.0
```

I'm trying to perform some HA tests with multiple master nodes,
The problem that I'm encountering is that when I shudown master components on master nodes (shutdown docker service and leave down), and I leave those down for some minutes, then when I re-start those masters( but not all, just 2/3 ( start docker service again )  the apiserver cluster come back online and all other components too, BUT some instances of weave not... 
in some nodes I get  the weave pod in "CrashLoopBackOff" with only 1 log line such as : 

```
# from kubectl describe pod... 
  2m    1m      5       kubelet, v5s2.net      spec.containers{weave}  Normal  Pulling         pulling image "weaveworks/weave-kube:2.0.4"
  1m    1m      1       kubelet, v5s2.net      spec.containers{weave}  Normal  Created         Created container with docker id 9a57ad8973ab; Security:[seccomp=unconfined]
  2m    1m      5       kubelet, v5s2.net      spec.containers{weave}  Normal  Pulled          Successfully pulled image "weaveworks/weave-kube:2.0.4"
  1m    1m      1       kubelet, v5s2.net      spec.containers{weave}  Normal  Started         Started container with docker id 9a57ad8973ab
  2m    6s      17      kubelet, v5s2.net      spec.containers{weave}  Warning BackOff         Back-off restarting failed docker container
  1m    6s      7       kubelet, v5s2.net                              Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "weave" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=weave pod=weave-net-0cbf3_kube-system(d81fd395-9f76-11e7-afe6-fa163e8ea49c)"

### from kubectl logs .. 
2017/09/22 14:40:58 Could not get peers: Get https://10.201.0.1:443/api/v1/nodes: dial tcp 10.201.0.1:443: getsockopt: connection refused
Failed to get peers

#from  docker logs -f 509f13f67733
2017/09/22 14:46:06 Could not get peers: Get https://10.201.0.1:443/api/v1/nodes: dial tcp 10.201.0.1:443: getsockopt: connection refused
Failed to get peers
```

on the nodes where weave doesn't restart, if i curl to https://10.201.0.1:443/ I get the timeout reponse from the node which is down , on nodes where weave recover correctly instead I get the correct reply from one of the  apiserver which is up.
now, if I delete the service `kubernetes` in `default` namespace , it gets recreated with only the two apiserver endpoints  that are online , BUT the weave still stand in this `CrashLoopBackOff` state... 

the situation is even worse..
even if I delete the pod from kubectl it doesn't work.. I'll perform more tests on monday probably,
when I then start the missing master that was still down, weave connect again,

I suspect that weave connect to one master and remain to this, or maybe watch for changes in default/kubernetes ? 

I think that  because when one of the master nodes is down, the default/kubernetes endpoints still remain 3, including the node that is down.. so shouldn't be trusted too much ...

```
Name:                   kubernetes
Namespace:              default
Labels:                 component=apiserver
                        provider=kubernetes
Annotations:            <none>
Selector:               <none>
Type:                   ClusterIP
IP:                     10.201.0.1
Port:                   https   443/TCP
Endpoints:              --IP1--:6443,--IP2--:6443,--IP3--:6443
Session Affinity:       ClientIP
Events:                 <none>
```
a solution I can think about is providing the apiserver endpoint manually,
each kubernetes HA  system to be really HA should have a loadbalancer ( nginx/hap/... ) pointing to apiserver, why I cannot tell weave to use those endpoints  instead of default.kubernetes.svc.... ? 
there is a way to specify different apiserver endpoint/service ?  I haven't found it in docs..

Thank you,
Francesco

**Comment by fvigotti** [comment]
Ok, probably I've found where is the problem.. which anyway I think should be fixed...

the problem is that weave configure iptables/nat to redirect randomly between apiservers ip,
BUT, it's a bit sticky about which ip to use,

this is the like that weave create
```
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-QGSNCIMMVIEBJLAU --mask 255.255.255.255 --rsource -j KUBE-SEP-QGSNCIMMVIEBJLAU
```
as you can see the timeout of the ip redirection is about  3 hours,
this means that in HA clusters, when a node is down, connections that was directed to the failed node/nodes will remain attached to it for 3 hours.. ( and maybe even more if weave doesn't try other apiserver destination when find a failed connection and still re-connecting to the failed one )  And because the service that configure iptables doesn't test the connection neither do the service that want to connect to the apiserver everything stays down 
I think that the service that connect to weave-apiserver should not rely on this iptables redirection because at the moment the failower logic for services doesn't seems to work for this specific service ( ip are not updated fast enough ) instead would be better if weave use the ip on dns resolution and attempt to connect to them directly ( maybe refreshing at given interval ) so he can failower correctly ,

summary:
At this point when one/some of the master nodes crashes , some client nodes crashes too because weave stay connected to the ip of this master nodes(even if more than half of masters are up ), and this is VERY VERY VERY bad... 

Thanks,
Francesco

**Comment by bboreham** [comment]
Thanks for the update.  I agree it shouldn't be behaving as you describe.

It would be `kube-proxy` creating those iptables rules.

The `could not get peers` message comes from a program that starts, does its job and exits, so it cannot be maintaining a connection.

**Comment by fvigotti** [comment]
Another solution that I can propose, is leaving a way to configure the apiserver IP address on weave ( with an env variables/cli-args  ) and this ip will point to my nginx loadbalancer that I have already have to setup for the kube-proxy instances in the cluster ( HA kubernetes require a custom webserver with failower  torwards api ip address, this is specified also in kubernetes official guides for HA cluster setup ) and so you could use this same services that anyway is required, to point weave to..

this will be a solution with very low coding, very effective and optional only to ones that are willing to use it.. ( those with a HA kubernetes cluster ) 

Thanks,
Francesco

**Comment by bboreham** [comment]
Weave Net connects to the Kubernetes api-server [as recommended here](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod); the address comes from environment variables configured within Kubernetes; you are free to set them as you wish.

**Comment by fvigotti** [comment]
Hi,
Maybe I've found what are you talking about.. and  experimenting for an elegant solution at the moment I have created a service to expose the nginx-ha which provide failover over various api-servers

```yml
apiVersion: v1
kind: Service
metadata:
  labels:
  name: nginxha
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-nginx
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6444 ## port exposed by nginx-ha and which reverse-proxy to api-servers
  sessionAffinity: ClientIP
  type: ClusterIP
  clusterIP: 10.201.0.1
```
then created a redirect to the just created services (wich exists in kube-system namespace ), this redirect will replace the kubernetes.default service which in all cluster is the default link for api-servers endpoints
```yml
apiVersion: v1
kind: Service
metadata:
  labels:
  name: kubernetes
  namespace: default
spec:
  type: ExternalName
  externalName: nginxha.kube-system.svc.cluster.local
```

then ,  **AND I DON'T KNOW WHY** weave started crashing with this error..
```
2017/09/25 12:26:41 Could not get peers: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Failed to get peers
``` 
which is strange because this is supposed to be provided by the kubernetes by default.. and the service is in place.. even restarting, and even recreating docker containers of weave and deleting the whole daemonset and recreating it didn't fixed.. at the end I've changed the default image of weave adding to both weave and weave-npc  those envs 
```yml
              env:
                - name: KUBERNETES_SERVICE_HOST
                  value: "10.201.0.1"
                - name: KUBERNETES_SERVICE_PORT
                  value: "443"
```

now with this all in place the cluster can survive a master failure in a multi-master cluster, 
probably setting a KUBERNETES_SERVICE_HOST directly to the ip of nginx-ha without overriding the default kubernetes.default service would be easier I'll try maybe in the future..
anyway I hope this thread could be helpful to someone else with same issue :)

Bye,
Francesco

**Comment by fvigotti** [comment]
Found a problem in the solution  here above, when a service with type `type: ExternalName` is used, the injected env variables become the first name of the redirected service name, not the name of the service which has the redirect,  this cause the problem with env variables in weave, aswell as missing kubernetes.default services in kubedns and other services that need it..

solution:
the nginx-ha service should be name "kubernetes" , so :  
```yml
apiVersion: v1
kind: Service
metadata:
  labels:
  name: kubernetes
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-nginx
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6444 ## port exposed by nginx-ha and which reverse-proxy to api-servers
  sessionAffinity: ClientIP
  type: ClusterIP
  clusterIP: 10.201.0.1
```

and the second service in default namespace should then be : 
```yml
apiVersion: v1
kind: Service
metadata:
  labels:
  name: kubernetes
  namespace: default
spec:
  type: ExternalName
  externalName: kubernetes.kube-system.svc.cluster.local
```
and everything works ;)
