### ISSUE TITLE
Service on StatefulSet pods in Default-deny namespace doesn't connect via Service's IP

### ISSUE THREAD

**Issue by RRAlex** [weaveworks/weave#3127]
## What you expected to happen?

A namespace with a default-deny policy, with a statefulSet of pods using the following NetworkPolicy:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: elasticsearch-logging-fluentd
  namespace: kube-system-logging
spec:
  podSelector:
    matchLabels:
      name: elasticsearch-logging
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: fluentd-es
      ports:
        - protocol: TCP
          port: 9200
```
... should let the ingress pods connect to the service's IP, resolved from its DNS.
ie: `elasticsearch-logging` (or `elasticsearch-logging.kube-system-logging.svc.cluster.local` or resolved IP) should be reachable from fluentd-es pods.

## What happened?

I'm unable to get a NetworkPolicy to work when using a deployment, daemonSet or StatefulSet using a service. 
As soon as a service is scaled and not just a single pod anymore, NetworkPolicy seems to stop working with the service IP. 
It does resolve, but doesn't connect to anything and timeouts.
```
root@fluentd-es-mgdr2:/# curl -v elasticsearch-logging:9200
* Rebuilt URL to: elasticsearch-logging:9200/
*   Trying 10.0.0.153...
* TCP_NODELAY set
^C
```

The elasticsearch pods' real IPs do go through, from any node...
```
root@fluentd-es-mgdr2:/# curl -v 10.1.0.26:9200
* Rebuilt URL to: 10.1.0.26:9200/
*   Trying 10.1.0.26...
* TCP_NODELAY set
* Connected to 10.1.0.26 (10.1.0.26) port 9200 (#0)
> GET / HTTP/1.1
> Host: 10.1.0.26:9200
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 348
< 
{
  "name" : "elasticsearch-logging-0",
  "cluster_name" : "kubernetes-logging",
  "cluster_uuid" : "lgMREbo0QS-4Oo_Er2l8Xw",
  "version" : {
    "number" : "5.5.1",
    "build_hash" : "19c13d0",
    "build_date" : "2017-07-18T20:44:24.823Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
* Curl_http_done: called premature == 0
* Connection #0 to host 10.1.0.26 left intact

root@fluentd-es-mgdr2:/# curl -v 10.1.96.29:9200
* Rebuilt URL to: 10.1.96.29:9200/
*   Trying 10.1.96.29...
* TCP_NODELAY set
* Connected to 10.1.96.29 (10.1.96.29) port 9200 (#0)
> GET / HTTP/1.1
> Host: 10.1.96.29:9200
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 348
< 
{
  "name" : "elasticsearch-logging-1",
  "cluster_name" : "kubernetes-logging",
  "cluster_uuid" : "lgMREbo0QS-4Oo_Er2l8Xw",
  "version" : {
    "number" : "5.5.1",
    "build_hash" : "19c13d0",
    "build_date" : "2017-07-18T20:44:24.823Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
* Curl_http_done: called premature == 0
* Connection #0 to host 10.1.96.29 left intact

```
For example, I get a service IP for elasticsearch:
```
NAME                        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE       SELECTOR
svc/elasticsearch-logging   10.0.0.153   <none>        9200/TCP,9300/TCP   7m        k8s-app=elasticsearch-logging
```
And strangely I see on a node that fluentd is hitting this firewall rule (constantly increasing counter, with or without elasticsearch on the same node):
```
8439  506K ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set weave-Ce/;?9|^:GN%qeffV/WRJVYf) src match-set weave-#g]y?HVptgRSeRO7?!ecAj#!c dst tcp dpt:9200 /* pods: namespace: kube-system-logging, selector: name=fluentd-es -> pods: namespace: kube-system-logging, selector: name=elasticsearch-logging */
```
And the corresponding `ipset list`:
(`ipvsadm` doesn't list anything. It's as if the virtual IP never got swapped for one of the 2 elasticsearch pods?)
```
Name: weave-#g]y?HVptgRSeRO7?!ecAj#!c
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 comment
Size in memory: 320 
References: 6
Members:
10.1.0.26 comment "namespace: kube-system-logging, pod: elasticsearch-logging-0"
10.1.128.26 comment "namespace: kube-system-logging, pod: elasticsearch-logging-1"
```
```
Name: weave-Ce/;?9|^:GN%qeffV/WRJVYf)
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 comment
Size in memory: 512
References: 1
Members:
10.1.0.27 comment "namespace: kube-system-logging, pod: fluentd-es-sh7zl"
10.1.128.25 comment "namespace: kube-system-logging, pod: fluentd-es-mgdr2"
10.1.96.28 comment "namespace: kube-system-logging, pod: fluentd-es-f0z3d"
10.1.192.16 comment "namespace: kube-system-logging, pod: fluentd-es-c738x"
```

## How to reproduce it?
Creating a NetworkPolicy for any scaled pod with a service attached to it seems to make it impossible to reach those pods via it's name (DNS) or its service's IP.

## Anything else we need to know?
```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system-logging
  labels:
    name: elasticsearch-logging
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - name: db
    port: 9200
    protocol: TCP
    targetPort: db
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    k8s-app: elasticsearch-logging
```
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-logging
  namespace: kube-system-logging
  labels:
    name: elasticsearch-logging
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: elasticsearch-logging
  labels:
    name: elasticsearch-logging
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system-logging
  name: elasticsearch-logging
  labels:
    name: elasticsearch-logging
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
subjects:
- kind: ServiceAccount
  name: elasticsearch-logging
  namespace: kube-system-logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-logging
  apiGroup: ""

---
# Elasticsearch deployment itself
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: kube-system-logging
  labels:
    name: elasticsearch-logging
    k8s-app: elasticsearch-logging
    version: v5.5.1
    kubernetes.io/cluster-service: "true"
spec:
  serviceName: elasticsearch-logging
  replicas: 2
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v5.5.1
  template:
    metadata:
      labels:
        name: elasticsearch-logging
        k8s-app: elasticsearch-logging
        version: v5.5.1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch-logging
      containers:
      - image: gcr.io/google-containers/elasticsearch:v5.5.1-1
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: elasticsearch-logging
        emptyDir: {}
```
fluentd deployment:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es
  namespace: kube-system-logging
  labels:
    name: fluentd-es
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
#   addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-es
  labels:
    name: fluentd-es
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
#   addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-es
  labels:
    name: fluentd-es
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
#   addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-es
  namespace: kube-system-logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-es
  apiGroup: ""
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-es
  namespace: kube-system-logging
  labels:
    name: fluentd-es
    k8s-app: fluentd-es
    version: v2.0.1
    kubernetes.io/cluster-service: "true"
#   addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        name: fluentd-es
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: v2.0.1
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: fluentd-es
      containers:
      - name: fluentd-es
        image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume
        configMap:
          name: fluentd-es
```
## Versions:
$ weave version
```
weave script 2.0.4
Unable to find weaveworks/weave:2.0.4 image.
```
$ docker version
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
$ uname -a
```
Linux staging-worker-001 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
## Logs:
```
Sep 21 17:14:38 localhost docker/k8s_weave-npc_weave-net-lfgdp_kube-system_33eee4d2-97ca-11e7-b6f6-fa163e692d92_0[26147]: WARN: 2017/09/21 21:14:38.237214 TCP connection from 10.1.0.1:46942 to 10.1.128.27:9200 blocked by Weave NPC.
Sep 21 17:14:39 localhost docker/k8s_weave-npc_weave-net-lfgdp_kube-system_33eee4d2-97ca-11e7-b6f6-fa163e692d92_0[26147]: WARN: 2017/09/21 21:14:39.315307 TCP connection from 10.1.96.0:33418 to 10.1.128.27:9200 blocked by Weave NPC.
Sep 21 17:14:39 localhost docker/k8s_weave-npc_weave-net-lfgdp_kube-system_33eee4d2-97ca-11e7-b6f6-fa163e692d92_0[26147]: WARN: 2017/09/21 21:14:39.315468 TCP connection from 10.1.192.0:59362 to 10.1.128.27:9200 blocked by Weave NPC.
```
