### ISSUE TITLE
qosclass for weave pods should be "Guaranteed"

### ISSUE THREAD

**Issue by fvigotti** [weaveworks/weave#3195]
all version, even the most recent "https://cloud.weave.works/k8s/v1.7/net"
will create pods with QoS: Burstable,
which is a NO-NO  because weave is the most important pod in the node , and this caused me some trouble when a node started eviction process ( kubelet now evict by default if some thresholds are reached ie : <10% disk free )  the kubelet removed weave pod and the whole node went down..

now, how to setup the QoS ? you can't directly ( see : https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/ ) you must provide strict resource requirement and the QoS Class Guaranteed will be assigned automatically 
so to all containers you should add something like 

```yaml
              resources:
                limits:
                  memory: "200Mi"
                  cpu: "300m"
                requests:
                  memory: "100Mi"
                  cpu: "30m"
```
and you will be fine :)
NB: adjust the limit , I don't know exactly what are your application minimum requirements, and maybe requests & limits should be equal ? 

anyway I think that the QoS Class:Guaranteed  for the weave main pod is a must for everyone..
