### ISSUE TITLE
DENY all traffic from other namespaces

### ISSUE THREAD

**Issue by raniatriki** [weaveworks/weave#3222]
**What you expected to happen?**

deny all the traffic from other namespaces while allowing all the traffic coming from the same namespace

**What happened?**

Traffic allowed from all namespaces

**How to reproduce it?**

Create a new namespace called ns-1 and start a web service:

```
kubectl create namespace secondary

kubectl run web --namespace ns-1--image=nginx \
    --labels=app=web --expose --port 80
```

Save the following manifest to web-deny-other-namespaces.yaml and apply to the cluster: 

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: ns-1
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

```
$ kubectl apply -f web-deny-from-other-namespaces.yaml
networkpolicy "deny-from-other-namespaces" created"
```

Query the web service from the default namespace:

```
$ kubectl run test-$RANDOM --namespace=default --rm -i -t --image=alpine -- sh
/ # wget -qO- --timeout=2 http://web.ns-1
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

So, It doesn't block the traffic from default namespace!.... but it should blocks it
