### ISSUE TITLE
Network policy does not work due to lack of a rolebinding

### ISSUE THREAD

**Issue by autumnw** [weaveworks/weave#3304]
## What you expected to happen?
I have k8s 1.10 installed with weave-net 2.2.1, the networkpolicy is not working as expected.
I have the policy like
```apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: pat1-global-staging
spec:
  podSelector: {}
  policyTypes:
  - Ingress```
I expected all the pods out of namespace 'pat1-global-staging' should NOT be able to acces the pods inside of namespace 'pat1-global-staging'.
## What happened?
But I still can access from the pods belong to different namepsace.

## How to reproduce it?
Just create a networkpolicy for one namepsace, then try to telnet to the pods belong to that namesapce from a pod which does not belong to that namespace.

## Anything else we need to know?
With help from stepan in slack channel, I created the following rolebinding, and it start working as expected:
```
kubectl create clusterrolebinding weave-net-cluster-admin \
    --clusterrole cluster-admin \
    --user system:serviceaccount:kube-system:weave-net
```
## Versions:
$ weave version 2.2.1
$ docker version ce-17.2
$ kubectl version  1.10
```

## Logs:
```
ERROR: logging before flag.Parse: E0525 14:40:29.693725    7558 reflector.go:205] github.com/weaveworks/weave/prog/weave-npc/main.go:230: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:kube-system:weave-net" cannot list networkpolicies.networking.k8s.io at the cluster scope
```

**Comment by bboreham** [comment]
How was Weave Net installed?  All of our installers have a rolebinding granting sufficient permissions, e.g. [here](https://github.com/weaveworks/weave/blob/master/prog/weave-kube/weave-daemonset-k8s-1.7.yaml#L44-L53)

**Comment by autumnw** [comment]
Hi,
I installed with the following yml file:
```yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-net
      labels:
        name: weave-net
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: weave-net
      labels:
        name: weave-net
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
          - namespaces
          - nodes
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - networkpolicies
        verbs:
          - get
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: weave-net
      labels:
        name: weave-net
    roleRef:
      kind: ClusterRole
      name: weave-net
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: Role
    metadata:
      name: weave-net-kube-peer
      namespace: kube-system
      labels:
        name: weave-net-kube-peer
    rules:
      - apiGroups:
          - ''
        resources:
          - configmaps
        resourceNames:
          - weave-net
        verbs:
          - get
          - update
      - apiGroups:
          - ''
        resources:
          - configmaps
        verbs:
          - create
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: weave-net-kube-peer
      namespace: kube-system
      labels:
        name: weave-net-kube-peer
    roleRef:
      kind: Role
      name: weave-net-kube-peer
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: weave-net
      labels:
        name: weave-net
      namespace: kube-system
    spec:
      template:
        metadata:
          labels:
            name: weave-net
        spec:
          containers:
            - name: weave
              command:
                - /home/weave/launch.sh
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: "sv3-docker.si.pan.local:443/weave-kube:2.2.1"
              livenessProbe:
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
                initialDelaySeconds: 30
              resources:
                requests:
                  cpu: 100m
                limits:
                  cpu: 100m
              securityContext:
                privileged: true
              volumeMounts:
                - name: weavedb
                  mountPath: /weavedb
                - name: cni-bin
                  mountPath: /host/opt
                - name: cni-bin2
                  mountPath: /host/home
                - name: cni-conf
                  mountPath: /host/etc
                - name: dbus
                  mountPath: /host/var/lib/dbus
                - name: lib-modules
                  mountPath: /lib/modules
            - name: weave-npc
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: "sv3-docker.si.pan.local:443/weave-npc:2.2.1"
              resources:
                requests:
                  cpu: 100m
                limits:
                  cpu: 100m
              securityContext:
                privileged: true
          hostNetwork: true
          hostPID: true
          imagePullSecrets:
          - name: internalpull
          restartPolicy: Always
          securityContext:
            seLinuxOptions: {}
          serviceAccountName: weave-net
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: weavedb
              hostPath:
                path: /var/lib/weave
            - name: cni-bin
              hostPath:
                path: /opt
            - name: cni-bin2
              hostPath:
                path: /home
            - name: cni-conf
              hostPath:
                path: /etc
            - name: dbus
              hostPath:
                path: /var/lib/dbus
            - name: lib-modules
              hostPath:
                path: /lib/modules
      updateStrategy:
        type: RollingUpdate
```
