### ISSUE TITLE
weave-kube: Cannot patch nodes/status at the cluster scope

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#3332]
Just spotted on a local cluster:

```
FATA: 2018/06/17 08:04:55.395186 [kube-peers] could not set node status: nodes "host1" is forbidden: User "system:serviceaccount:kube-system:weave-net" cannot patch nodes/status at the cluster scope
```

Seems that the following is not set in the latest Weave Net DS and launch-generator:

```
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
  - update
```

(Taken from https://github.com/weaveworks/weave/issues/3249#issuecomment-369653750)
