### ISSUE TITLE
weave-npc: error: assignment to entry in nil map

### ISSUE THREAD

**Issue by kirikaza** [weaveworks/weave#3407]
**BUG REPORT**

## What you expected to happen?
weave-npc logs shouldn't contain errors

## What happened?
```
ERROR: logging before flag.Parse: E0918 14:07:47.578681    3471 runtime.go:66] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/go/src/github.com/weaveworks/weave/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/weaveworks/weave/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/weaveworks/weave/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/hashmap.go:507
/go/src/github.com/weaveworks/weave/npc/selector.go:157
/go/src/github.com/weaveworks/weave/npc/namespace.go:396
/go/src/github.com/weaveworks/weave/npc/controller.go:161
/go/src/github.com/weaveworks/weave/npc/controller.go:78
/go/src/github.com/weaveworks/weave/npc/controller.go:160
/go/src/github.com/weaveworks/weave/prog/weave-npc/main.go:306
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/controller.go:209
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/controller.go:320
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/controller.go:150
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/controller.go:124
/go/src/github.com/weaveworks/weave/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/weaveworks/weave/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/weaveworks/weave/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/github.com/weaveworks/weave/vendor/k8s.io/client-go/tools/cache/controller.go:124
/usr/local/go/src/runtime/asm_amd64.s:2361
```

## How to reproduce it?
I couldn't reproduce it again. First time I played with network policies, creating and deleting them. These policies were simple: "deny all ingress", "deny all egress", "allow ingress to A from B", "allow egress from B to A".

## Versions:

```
$ kubectl exec -n kube-system weave-net-… -c weave -- /home/weave/weave --local version
weave 2.4.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ minikube version
minikube version: v0.28.2
```
minikube cluster has been created according to [this note](https://github.com/weaveworks/weave/issues/3124#issuecomment-397820940).

## Logs:
`$ kubectl logs -n kube-system weave-net-… weave-npc` — see [the gist](https://gist.github.com/kirikaza/ef677b3940fe24e7c53be5fa5c837ee3#file-weave-net-vmln8-weave-npc-log-L189-L212).

**Comment by kirikaza** [comment]
`deny-ingress.yaml`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
```

`deny-egress.yaml`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

`nginx-from-redis.yaml`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-from-redis
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: redis
```

`redis-to-nginx.yaml`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-to-nginx
spec:
  podSelector:
    matchLabels:
      app: redis
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: nginx
```
