### ISSUE TITLE
Install on K8S

### ISSUE THREAD

**Issue by stgleb** [weaveworks/weave#3618]
I follow official doc [link](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/) to install weave on kubernetes, but I would like to have ability to dump net.yaml on my computer rather than download it all the time(because of firewall issues). Is there any workaround for that?

## How to reproduce it?
 download net.yaml 

`https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')` and save it.

`kubectl apply -f <filename>`

## Versions:

```
kubectk version

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
docker version

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:18 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

uname -a

```
Linux ip-10-2-82-155 4.4.0-1065-aws #75-Ubuntu SMP Fri Aug 10 11:14:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

When run

```
kubectl create -f weave.yaml 
error: error validating "weave.yaml": error validating data: [ValidationError(ClusterRole.rules[0].apiGroups): unknown object type "nil" in ClusterRole.rules[0].apiGroups[0], ValidationError(ClusterRole.rules[2].apiGroups): unknown object type "nil" in ClusterRole.rules[2].apiGroups[0], ValidationError(Role.rules[0].apiGroups): unknown object type "nil" in Role.rules[0].apiGroups[0], ValidationError(Role.rules[1].apiGroups): unknown object type "nil" in Role.rules[1].apiGroups[0]]; if you choose to ignore these errors, turn validation off with --validate=false
```

But 

```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

works fine

**Comment by murali-reddy** [comment]
How does the `ClusterRole` rbac rules stanza looks like in downloaded manifest? It should be like below

```yaml
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
          - namespaces
          - nodes
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - networking.k8s.io
        resources:
          - networkpolicies
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ''
        resources:
          - nodes/status
        verbs:
          - patch
          - update

```

It should be same manifest whether you download and apply or apply directly.
