### ISSUE TITLE
npc blocking traffic coming via nodePort service

### ISSUE THREAD

**Issue by deitch** [weaveworks/weave#3642]
Note: moving from [comments beginning here](https://github.com/weaveworks/weave/issues/2997#issuecomment-491036164). May be related to #3383 but unsure.

Original issue was discussed with @bboreham (who resolved it too :-) )

## What you expected to happen?

Traffic should be allowed there, at least compliant with networkpolicy

## What happened?

Traffic blocked, even if port explicitly allowed in networkpolicy

## How to reproduce it?

1. Create a deployment with a port
2. Create a service pointing to it with `nodePort`
3. Create a network policy allowing access _only_ to the specific port and `nodePort`
4. Results:
    * Pod-to-pod traffic to the pod IP and pod port is allowed (CORRECT)
    * Pod-to-pod traffic to the service IP and service port is allowed (CORRECT)
    * Pod-to-pod traffic to the host IP and nodePort is blocked (what appears incorrect to me)
    * External-to-pod traffic to the host IP and nodePort is blocked (what appears incorrect to me)

Samples:

```yml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30080
  selector:
    name: nginx
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-pod-port-and-nodeport
spec:
  podSelector:
    matchLabels:
      name: nginx
  ingress:
  - ports:
    - port: 80
    - port: 30080
    from:
    - podSelector:
        matchLabels: {}
```

Launch the above, then try the following:

* Launch another pod, `curl <pod IP>:80` - works
* Launch another pod, `curl <node IP>:30080` - blocked
* From  another host or even on the host itself, `curl <node IP>:30080` - blocked

FWIW, to make life easier, here are the logs from my npc when running the above. In my case, it was kafka, so the pod port is `9092` and nodePort is `30093`, but the idea is the same:

```
WARN: 2019/05/09 19:14:28.236915 TCP connection from 10.50.22.140:54624 to 10.51.24.5:9092 blocked by Weave NPC.
```

FYI, `10.51.24.5` is one of the kafka pods (with port `9092`), and `10.50.22.140` is one of the worker nodes (where the source pod trying to reach kafka exists).

## Anything else we need to know?

tried with versions 2.2.x and 2.5.x of weave.

Specific use case here is kafka running as a service on Kubernetes that is providing service both to other pods in-cluster and external services. Kafka's (interesting) protocol is that you bootstrap by making an initial connection to Kafka, which reports back the broker IPs and ports. Thus, you need a consistent `IP:port` (or `hostname:port`) scheme to report, which will be used both by in-cluster clients and out-of-cluster clients. This means you _must_ use the host IP and the `nodePort`. However, this breaks networkpolicy.

**Comment by murali-reddy** [comment]
Considering the issues with how [services fit in to network policies](https://groups.google.com/forum/#!topic/kubernetes-sig-network/-bLIwKdkHvI) everything is working as expected. 

So below lines in the network policy is what is causing issue for you.

```
    from:
    - podSelector:
        matchLabels: {}
```
Since you explicitly mentioned (with the use of podSelector) which pods should get access, access from any other IP not matching the IP's of pods selected by `matchLabels` are blocked.

Try taking out that stanza from network policy, and check the behaviour which should allow traffic from everywhere.

For the failing cases you mentioned, its due to fact traffic getting masquraded resulting in IP address which does not match the IP's selected by the pod selector.

**Comment by deitch** [comment]
> Since you explicitly mentioned (with the use of podSelector) which pods should get access, access from any other IP not matching the IP's of pods selected by matchLabels are blocked
>
> traffic getting masquraded resulting in IP address which does not match the IP's selected by the pod selector

Let me see if I get this. When a networkpolicy with `from: podSelector: matchLabels:` is applied, the `npc` (which implements the networkpolicy) essentially does the following:

1. look up the IP addresses of all pods that match the `podSelector`
2. check if the src IP of the packet is in that list. If it is, let it through; if not, do not

As such, everything else - including the host IP of pod A's host, which is getting masqueraded because of using the host IP of pod B's host and `nodePort`, as well as any outside source - will get blocked.

Thus, it isn't a question of a bug, but syntax.

This syntax means: let in all pods, but not anything else:

```yml
from:
- podSelector:
    matchLabels: {}
```

If we want _all_ traffic - both from in-cluster and off-cluster (why is the opposite of "in-cluster" called "off-cluster"? Should it not be "out-cluster"? :-) ) - then we need a different syntax. We could use no `NetworkPolicy`, but if you have a default deny all, or have a corporate policy requiring networkpolicy, or just want to safely block all except specific ports, that won't work.

So what _is_ the correct syntax then? Without any `from:`, will it not block everything?
