### ISSUE TITLE
Configure hostname alias for a container using docker-compose with weavenet

### ISSUE THREAD

**Issue by avkonst** [weaveworks/weave#3826]
This ticket is a question. There is well circulated information how to run a container by docker-compose and attach it to weave network. Using the example from here: https://github.com/avkonst/overnode/blob/master/examples/nginx/nginx.yml it would be:

```yml
version: '3.7'
services:
    nginx:
        container_name: nginx
        hostname: nginx.weave.local
        image: nginx
        network_mode: bridge
        init: true
        ports:
            - 80:80
        restart: always
```

However, I can not figure out how to add hostname alias (same as `--alias` argument for `docker run`) for the same container using the compose configuration and weave network. I would like both hostname and the alias be registered in weavenet DNS. 

Could you please advise what the right configuration section for the alias should be?
