### ISSUE TITLE
NetworkPolicy Egress ipBlock+except not working for same node internal IP

### ISSUE THREAD

**Issue by wuestkamp** [weaveworks/weave#3924]
When I apply the following NP I would expect that Pods won't be able to connect to 11.11.11.11 and 22.22.22.22

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: firewall
  namespace: my-namespace
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 11.11.11.11/32 # controlplane internal IP
          - 22.22.22.22/32 # worker node internal IP
```

But a Pod running on the worker node 22.22.22.22 can still connect to 22.22.22.22. Connections to 11.11.11.11 are blocked.

Is this expected behaviour with Weave or something wrong on my setup?

weave: 2.8.1
k8s: 1.22.1
