### ISSUE TITLE
Opening up development of Weave Net

### ISSUE THREAD

**Issue by dholbach** [weaveworks/weave#3948]
To those of you who responded in the discussion of #3939, thanks a lot for your ideas and offers of help so far! :sparkling_heart: 

Weaveworks wants to open up the development of Weave Net and in order to bring interested folks together, get to know each other and discuss ideas, we would like to arrange a meeting soon. :calendar: 

If you are interested in joining, please comment on this issue, so we can let you know when it's going to happen, or give you a ping for a doodle we've set up. Thanks a lot everyone in advance!

CCing @monadic and @kingdonb

**Comment by rajibmitra** [comment]
@dholbach - I would like to join, please add me to the meeting.

**Comment by rajch** [comment]
I am interested. Thank you.

**Comment by monadic** [comment]
Hi would folks be able to meet next week on 9 AUGUST at 3pm UK time?

**Comment by taigrr** [comment]
I am interested.

**Comment by jscottsf** [comment]
Same here. Interested.

**Comment by monadic** [comment]
Great -- here is the Meeting URL to join 

Weave Net community meeting
Wednesday, August 10 · 4:00 – 4:40pm UK (8am US Pacific)

Google Meet joining info
Video call link: https://meet.google.com/ydc-wwtn-xye
Or dial: ‪(GB) +44 20 3910 5019‬ PIN: ‪732 425 366‬#
More phone numbers: https://tel.meet/ydc-wwtn-xye?pin=1413075876243

**Comment by monadic** [comment]
Next meeting 31 August!

weave net open meeting
Wednesday, August 31 · 4:00 – 4:50pm
Google Meet joining info
Video call link: https://meet.google.com/fjy-msnk-fcq
Or dial: ‪(GB) +44 20 3956 9319‬ PIN: ‪208 155 944‬#
More phone numbers: https://tel.meet/fjy-msnk-fcq?pin=2035335265953

**Comment by monadic** [comment]
So the next steps:
* we have a core group of 3 people who want to move the community forward
* we want to get this to 10 or more
* weaveworks will support as much as possible - our only asks are "goes into CNCF" and we are all good community members!

-alexis

**Comment by monadic** [comment]
comments welcome people

**Comment by richardcase** [comment]
Would love to also help with this if it isn't too late 🤞

**Comment by jmickey** [comment]
Count me in as well!

**Comment by monadic** [comment]
> Which of the following do we need most at this point? 
> 
> 1) Regular maintenance, release publishing, documentation updates, pull request curation, regressions against newer library versions etc.
> 2)  Further development, feature additions etc.
> 3) Creation of new processes and structures to make the project more suitable for community participation and CNCF inclusion.
> 
> I think that, at this point, (1) is most important - just to keep weave net where it is. Maybe interested community members can begin by sharing some of that responsibility.
> 
> Sorry I missed the meeting. Mistimed it by one hour because of a silly timezone mistake.
> 

1 is the most important!

**Comment by jscottsf** [comment]
I would agree (1). Triage on issues, fix high priority ones, also update dependencies.

**Comment by richardcase** [comment]
I think the order listed is spot on.

**Comment by richardcase** [comment]
> Wednesday, August 31 · 4:00 – 4:50pm

@monadic - Is this BST?

**Comment by monadic** [comment]
Yes

**Comment by monadic** [comment]
thank you to @rajch @nathanejohnson and others for help and enthusiasm so far

this is the PLAN

1) we shall make a community document that states the goals for the next 6-12 months
2) priority is maintenance and regaining momentum as a self-sustaining community
3) we shall have a monthly open community meeting online to discuss and vote on a PUBLIC ROADMAP which will lay out near term priorities, how to help etc
4) step one is that I shall work on this with @rajch @nathanejohnson who will post link below so that others can help
5) overall aim is to get to X new maintainers by time (some time in 2023) to be determined
6) governance will aim to cede more control as trust builds up until the project is governed by a strong community 
7) ex maintainers have offered to help with this process

next public meeting will be 28 Sep at 4pm UK // 8am Pacific

--alexis

**Comment by rajch** [comment]
I have written up a basic outline for the roadmap [here](https://docs.google.com/document/d/13d-Q3wAeV0-wI_VOIPPR-XN9WlErVs8IRF_lO6r8lfw/edit?usp=sharing). Just broad headings, with a few points that I thought of. If the structure is okay, I shall continue to fill it in. 

The Google doc is public editable. Feel free to jump in.

**Comment by monadic** [comment]
added some text!

**Comment by rajch** [comment]
Some things that we can do should do with the aim of CNCF inclusion:

1) Start gathering a list of adopters (people or projects that are using weave net right now). See [here](https://github.com/cncf/toc/blob/main/FAQ.md#what-is-the-definition-of-an-adopter) for a definition of "adopter".
2) Consider adopting the CNCF [code of conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

In the long term, the CNCF [IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy) will need to be considered, as well.

Full details about the graduation process can be found [here](https://github.com/cncf/toc/blob/main/process/graduation_criteria.md).

**Comment by rajch** [comment]
I've been disconnected for a bit. Did the public meeting on 28th September happen? What did I miss?

**Comment by rajch** [comment]
## Proposal for new install endpoint

The recommended method for installing weave used to be this:

```
kubever=$(kubectl version | base64 | tr -d '\n')
kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$kubever
```
This would redirect to the simpler url:
```
https://cloud.weave.works/k8s/vX.YZ/net.yaml
```
which would generate a manifest appropriate to the version of kubernetes. In the current release of weave (2.8.1), there are four possible manifests: `weave-daemonset-k8s-1.8.yaml`,  `weave-daemonset-k8s-1.9.yaml`, `weave-daemonset-k8s-1.11.yaml`, and `weave-daemonset-k8s.yaml`. The last one was added recently, and the documentation was updated to use that from the release, like this:

```
kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
```

I propose that the community create and maintain an endpoint like the old https://cloud.weave.works/k8s one, to ensure that the endpoint remains the same for potential future releases of both weave and kubernetes. This could re-use the old weave cloud code, or be a fresh implementation.

I can take this up if other people think this is a good idea.

**Comment by richardcase** [comment]
Is anyone going to Kubecon NA? Perhaps we could meetup if there are a few of us going?

**Comment by monadic** [comment]
@rajch ?

**Comment by rajch** [comment]
Sadly, not going. :disappointed:

**Comment by rajch** [comment]
> ## Proposal for new install endpoint

So I set up an experimental install endpoint, which works with both URL patterns mentioned above. I've tried to be as faithful to the old `https://cloud.weave.works/k8s` endpoint behaviour as I could remember. The new endpoint is currently hosted on a Free-tier Azure Web App, accessible at `https://weave-community-downloader.azurewebsites.net/`.

Weave can now be installed on a kubernetes cluster using:

```bash
kubever=$(kubectl version | base64 | tr -d '\n')
kubectl apply -f https://weave-community-downloader.azurewebsites.net/k8s/net?k8s-version=$kubever
```
OR

```bash
kubectl apply -f https://weave-community-downloader.azurewebsites.net/k8s/v1.25/net.yaml
```
where the `v1.25` part can be replace with any kubernetes version down to 1.8.

Source code here:  [https://github.com/rajch/weave-endpoint](https://github.com/rajch/weave-endpoint)

If it's good enough, maybe we could find a friendlier URL for it :grin:

**Comment by ledzepppelin** [comment]
what about other options? like setting MTU or disbling NPC? will they work on new endpoint?

**Comment by rajch** [comment]
They will, by the next version. I'll post progress here.

**Comment by rajch** [comment]
Some options have now been implemented: specifically, environment variables (MTU can be set using this) and seLinux options. Like I said, I need a bit of help for the others, like disabling NPC. If anyone remembers the old behaviour, or has the generated yaml, it would help. Meanwhile, I will try to reverse engineer using the official weave-kube image.

See the GitHub README for details.

**Comment by ledzepppelin** [comment]
this one is pretty old though @rajch 
```
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=1.16&disable-npc=true",
              "date": "Wed Sep 09 2020 13:33:36 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=1.16&disable-npc=true",
              "date": "Wed Sep 09 2020 13:33:36 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
          - namespaces
          - nodes
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - networking.k8s.io
        resources:
          - networkpolicies
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ''
        resources:
          - nodes/status
        verbs:
          - patch
          - update
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=1.16&disable-npc=true",
              "date": "Wed Sep 09 2020 13:33:36 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
    roleRef:
      kind: ClusterRole
      name: weave-net
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=1.16&disable-npc=true",
              "date": "Wed Sep 09 2020 13:33:36 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
    rules:
      - apiGroups:
          - ''
        resourceNames:
          - weave-net
        resources:
          - configmaps
        verbs:
          - get
          - update
      - apiGroups:
          - ''
        resources:
          - configmaps
        verbs:
          - create
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=1.16&disable-npc=true",
              "date": "Wed Sep 09 2020 13:33:36 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
    roleRef:
      kind: Role
      name: weave-net
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=1.16&disable-npc=true",
              "date": "Wed Sep 09 2020 13:33:36 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
    spec:
      minReadySeconds: 5
      selector:
        matchLabels:
          name: weave-net
      template:
        metadata:
          labels:
            name: weave-net
        spec:
          containers:
            - name: weave
              command:
                - /home/weave/launch.sh
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: EXPECT_NPC
                  value: '0'
              image: 'docker.io/weaveworks/weave-kube:2.7.0'
              readinessProbe:
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
              securityContext:
                privileged: true
              volumeMounts:
                - name: weavedb
                  mountPath: /weavedb
                - name: cni-bin
                  mountPath: /host/opt
                - name: cni-bin2
                  mountPath: /host/home
                - name: cni-conf
                  mountPath: /host/etc
                - name: dbus
                  mountPath: /host/var/lib/dbus
                - name: lib-modules
                  mountPath: /lib/modules
                - name: xtables-lock
                  mountPath: /run/xtables.lock
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          hostPID: true
          priorityClassName: system-node-critical
          restartPolicy: Always
          securityContext:
            seLinuxOptions: {}
          serviceAccountName: weave-net
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
          volumes:
            - name: weavedb
              hostPath:
                path: /var/lib/weave
            - name: cni-bin
              hostPath:
                path: /opt
            - name: cni-bin2
              hostPath:
                path: /home
            - name: cni-conf
              hostPath:
                path: /etc
            - name: dbus
              hostPath:
                path: /var/lib/dbus
            - name: lib-modules
              hostPath:
                path: /lib/modules
            - name: xtables-lock
              hostPath:
                path: /run/xtables.lock
                type: FileOrCreate
      updateStrategy:
        type: RollingUpdate
```
