### ISSUE TITLE
What's weave behavior in a multi-NIC kubernetes cluster?

### ISSUE THREAD

**Issue by DesireWithin** [weaveworks/weave#3958]
## Background
First of all, my kubernetes cluster is working well.
I have several kubernetes clusters `1.18.16`. They are deployed on virtual Ubuntu`18.04` servers.
kubernetes clusters are installed by kubeadm, weave net is installed by
`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`
weave version is `weave-kube:2.8.1`
Each Linux server has three network card, for example:
```
$> cat /etc/netplan/01-netcfg.yaml
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
          eno1:
                  dhcp4: no
                  dhcp6: no
                  addresses: [10.65.64.4/24]
          eno2:
                  dhcp4: no
                  dhcp6: no
                  addresses: [10.65.62.4/24]
                  gateway4: 10.65.62.254
                  nameservers:
                          addresses: [10.65.136.79,114.114.114.114]
          eno3:
                  dhcp4: no
                  dhcp6: no
                  addresses: [10.65.63.4/24]
```
I happened to find that one k8s cluster shows that node's `INTERNAL-IP` is in different network segment: 
```
$> kubectl get nodes -o wide
NAME               STATUS   ROLES    AGE    VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
dev-m-k8smaster2   Ready    master   555d   v1.18.16   10.65.64.20   <none>        Ubuntu 18.04.5 LTS   4.15.0-143-generic   docker://19.3.15
dev-m-k8sworker1   Ready    <none>   555d   v1.18.16   10.65.64.2    <none>        Ubuntu 18.04.5 LTS   4.15.0-140-generic   docker://19.3.14
dev-m-k8sworker2   Ready    <none>   555d   v1.18.16   10.65.62.4    <none>        Ubuntu 18.04.5 LTS   4.15.0-140-generic   docker://19.3.14
```
Please note that only `dev-m-k8sworker2` ip is `10.65.62.X/24`. I checked other clusters, other nodes' `INTERNAL-IP` are all `10.65.64.X/24`

## What did I do
After I check my installation steps and kubeadm&kubelet document, I didn't find any configuration for node IP. I am more inclined to think that it is set by weave:

1. I check `kubeadm init` and `kubeadm join` commands which I ran, there are no node IP settings.
2. I found a [kubelet document](https://kubernetes.io/docs/concepts/architecture/nodes/#self-registration-of-nodes), show that kubelet should run with a `--node-ip` flag. I checked my kubelet on `dev-m-k8sworker2`, kubelet is run as 
    `/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=docker.mycompany.net/google_containers/pause:3.2 --resolv-conf=/run/systemd/resolve/resolv.conf`
   I don't find any relevant nodeIP in `/etc/kubernetes/bootstrap-kubelet.conf` or `/etc/kubernetes/kubelet.conf ` or `/var/lib/kubelet/config.yaml `
3. I run command in  pod weave-net-c444k(locate at `dev-m-k8sworker2` ), container weave:
    ```
    $> /home/weave # /home/weave/weave --local status
        Version: 2.8.1 (failed to check latest version - see logs; next check at 2022/09/01 04:26:48)
        Service: router
        Protocol: weave 1..2
        Name: be:b8:93:58:7f:9e(dev-m-k8sworker2)
        Encryption: disabled
        PeerDiscovery: enabled
        Targets: 2
        Connections: 3 (2 established, 1 failed)
        Peers: 3 (with 6 established connections)
        TrustedSubnets: none
        Service: ipam
        Status: ready
        Range: 172.18.0.0/16
        DefaultSubnet: 172.18.0.0/16
    ```
      and

    ```
    $> /home/weave/weave --local status connections
    <- 10.65.62.20:58015     established fastdp f2:95:bf:e0:8f:df(dev-m-k8smaster2) mtu=1376
    -> 10.65.64.2:6783       established fastdp d2:e9:38:cb:23:14(dev-m-k8sworker1) mtu=1376
    -> 10.65.64.20:6783      failed      Multiple connections to f2:95:bf:e0:8f:df(dev-m-k8smaster2) added to be:b8:93:58:7f:9e(dev-m-k8sworker2), retry: 2022-09-01 06:34:07.393313755 +0000 UTC m=+3089879.835509712
     ```
     You can see the weave connections in built on 10.65.62.X/24, and `10.65.64.X/24` is rejected and retrying. There are also logs:
    ```
    INFO: 2022/09/01 04:33:02.232606 ->[10.65.64.20:6783] attempting connection
    INFO: 2022/09/01 04:33:02.235754 ->[10.65.64.20:6783|f2:95:bf:e0:8f:df(dev-m-k8smaster2)]: connection ready; using protocol version 2
    INFO: 2022/09/01 04:33:02.235864 overlay_switch ->[f2:95:bf:e0:8f:df(dev-m-k8smaster2)] using fastdp
    INFO: 2022/09/01 04:33:02.235914 ->[10.65.64.20:6783|f2:95:bf:e0:8f:df(dev-m-k8smaster2)]: connection shutting down due to error: Multiple connections to f2:95:bf:e0:8f:df(dev-m-k8smaster2) added to be:b8:93:58:7f:9e(dev-m-k8sworker2)
    INFO: 2022/09/01 04:38:37.175592 ->[10.65.62.2:38599] connection accepted
    INFO: 2022/09/01 04:38:37.176368 ->[10.65.62.2:38599|d2:e9:38:cb:23:14(dev-m-k8sworker1)]: connection ready; using protocol version 2
    INFO: 2022/09/01 04:38:37.176515 overlay_switch ->[d2:e9:38:cb:23:14(dev-m-k8sworker1)] using fastdp
    INFO: 2022/09/01 04:38:37.176574 ->[10.65.62.2:38599|d2:e9:38:cb:23:14(dev-m-k8sworker1)]: connection shutting down due to error: Multiple connections to d2:e9:38:cb:23:14(dev-m-k8sworker1) added to be:b8:93:58:7f:9e(dev-m-k8sworker2) 
    ```

## My qustions:
   
   1. Why this weave connection established on `10.65.62.X/24` rather than `10.65.64.X/24` or `10.65.63.X/24`?
   2. How should I control Node `internalIP`?
   3. Are there any offical document describe multiple network interface card situation?

Any guide will be appreciated.

**Comment by DesireWithin** [comment]
After read this [blog](https://thenewstack.io/how-to-navigate-multiple-networks-for-kubernetes-workloads/), I realize that I know very little about multi-NIC kubernetes clusters.
And I find a similar issue #3588 .
From this [comment](https://github.com/weaveworks/weave/issues/3588#issuecomment-457961835), I notice that weave can't not specify a specific NIC like flannel `--iface` or calico `IP_AUTODETECTION_METHOD`. Am I right? Are there any related document? (So is weave suitable as default CNI plugin in multi-NIC kubernetes clusters?)

I check kubernetes configuration again, here is some important snippet I think:
```
root@dev-m-k8smaster2:/etc/kubernetes/manifests# cat /etc/kubernetes/manifests/kube-apiserver.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.65.62.20:6443
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.65.62.20
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
...
  hostNetwork: true
...
```

And here is `kubelet` config from `dev-m-k8sworker2`

```
root@dev-m-k8sworker2:/etc/kubernetes# cat kubelet.conf
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://k8s.mycompany.net:6443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
...

```
Notice that `k8s.mycompany.net` is resolved as `10.65.63.20`.
Still, I don't konw why kubernetes pick up `10.65.64.X/24` as node `internalIP`. 
And how to resolve `Multiple connections` issue in my weave logs?


Sorry for I submit reckless issue here, and sorry for my poor knowleage of kubernetes.
Any documents and guidance will be appreciated.
