### ISSUE TITLE
Network 10.42.0.0/16 overlaps with existing route 10.42.139.128/26 on host

### ISSUE THREAD

**Issue by 631068264** [weaveworks/weave#3987]
## What happened?

```
kubectl logs -f pod/weave-net-4tw8g -n kube-system

Defaulted container "weave" out of: weave, weave-npc, weave-plugins, weave-init (init)
Network 10.42.0.0/16 overlaps with existing route 10.42.139.128/26 on host

```

daemonset yaml
```
        env:
        - name: INIT_CONTAINER
          value: "true"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: IPALLOC_RANGE
          value: 10.42.0.0/16
        - name: WEAVE_PASSWORD
          value: N4xxxxxxxxxxWu
        image: weaveworks/weave-kube:2.8.1
        imagePullPolicy: IfNotPresent
        name: weave
```

## How to reproduce it?

use rke build k8s 1.23.6

cluster.yml
```
network:
  plugin: weave
  weave_network_provider:
    password: 'N4xxxxxxxxWu'
```

## Versions:

```
$ weave version  2.8.1
$ docker version  19.03.11
$ uname -a    Linux server-44904695-b3bc-4721-8bad-725d6497a69a 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version    v1.23.6
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

## Network:

$ ip route

```
default via 172.17.7.254 dev eth0 
blackhole 10.42.139.128/26 proto bird 
10.42.225.192/26 via 172.17.7.53 dev tunl0 proto bird onlink 
169.254.169.254 via 172.17.7.2 dev eth0 proto static 
172.17.7.0/24 dev eth0 proto kernel scope link src 172.17.7.57 
172.18.0.0/16 dev docker0 proto kernel scope link src 172.18.0.1 
```

$ ip -4 -o addr
```
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 172.17.7.57/24 brd 172.17.7.255 scope global dynamic eth0\       valid_lft 57457sec preferred_lft 57457sec
3: docker0    inet 172.18.0.1/16 brd 172.18.255.255 scope global docker0\       valid_lft forever preferred_lft forever
39: tunl0    inet 10.42.139.128/32 scope global tunl0\       valid_lft forever preferred_lft forever
```
$ sudo iptables-save
